[package]
name = "oneko"
version = "0.1.0"
edition = "2024"

[dependencies]
mouse_position = "0.1.4"
winit = "0.28"
pixels = "0.13.0"
gif = "0.12"
image = "0.24"
tray-icon = "0.5"
window-vibrancy = "0.3"
